### ISSUE TITLE
Error running webpack

### ISSUE THREAD

**Issue by noflag** [Nullchan/nullchan#7]
webpack
Hash: c7a995dd9772ee870d5b
Version: webpack 1.12.14
Time: 8254ms
      Asset   Size  Chunks             Chunk Names
nullchan.js  16 kB       0  [emitted]  main
   [0] ./js/index.js 277 bytes {0} [built] [7 errors]
   [6] ./js/libs/md5.js 8.54 kB {0} [built]
    + 9 hidden modules

ERROR in ./js/engine/markup.jsx
Module parse failed: /home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-loader/index.js!/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/js/engine/markup.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import Helpers from "../libs/helpers.jsx";
| 
| const URL_REGEXP = /[-a-zA-Z0-9@:%_\+.~#?&amp;\/\/=]{2,256}\.?[a-z]{2,4}\b([\/:][-a-zA-Z0-9@:%_\+.~#?&amp;\/\/=!]*){1,}/mg;
 @ ./js/index.js 2:0-30

ERROR in ./js/engine/view.jsx
Module build failed: SyntaxError: /home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/js/engine/view.jsx: Unexpected token (34:35)
  32 | 
  33 |   renderHeader (siteInfo) {
> 34 |     this.rHeader = ReactDOM.render(<Header siteInfo={Nullchan.siteInfo} board={ {} }/>, this.header)
     |                                    ^
  35 |   }
  36 | 
  37 |   updateHeader () {
    at Parser.pp.raise (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:1378:13)
    at Parser.pp.unexpected (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:2817:8)
    at Parser.pp.parseExprAtom (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:749:12)
    at Parser.pp.parseExprSubscripts (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:504:19)
    at Parser.pp.parseMaybeUnary (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:484:19)
    at Parser.pp.parseExprOps (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:415:19)
    at Parser.pp.parseMaybeConditional (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:397:19)
    at Parser.pp.parseMaybeAssign (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:360:19)
    at Parser.pp.parseExprListItem (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:1206:16)
    at Parser.pp.parseCallExpressionArguments (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:580:20)
    at Parser.pp.parseSubscripts (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:543:29)
    at Parser.pp.parseExprSubscripts (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:514:15)
    at Parser.pp.parseMaybeUnary (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:484:19)
    at Parser.pp.parseExprOps (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:415:19)
    at Parser.pp.parseMaybeConditional (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:397:19)
    at Parser.pp.parseMaybeAssign (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:360:19)
    at Parser.pp.parseMaybeAssign (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:383:23)
    at Parser.pp.parseExpression (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:324:19)
    at Parser.pp.parseStatement (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:1874:19)
    at Parser.pp.parseBlockBody (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:2208:21)
    at Parser.pp.parseBlock (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:2189:8)
    at Parser.pp.parseFunctionBody (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:1125:22)
    at Parser.pp.parseMethod (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:1094:8)
    at Parser.pp.parseClassMethod (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:2495:8)
    at Parser.pp.parseClassBody (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:2456:10)
    at Parser.pp.parseClass (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:2339:8)
    at Parser.pp.parseStatement (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:1813:19)
    at Parser.pp.parseBlockBody (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:2208:21)
    at Parser.pp.parseTopLevel (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:1747:8)
    at Parser.parse (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:1349:17)
    at Object.parse (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/node_modules/babylon/index.js:45:50)
    at File.parse (/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-core/lib/transformation/file/index.js:479:24)
 @ ./js/index.js 3:0-28

ERROR in ./js/engine/images.jsx
Module parse failed: /home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-loader/index.js!/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/js/engine/images.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| export default class Images {
|   static process(formData) {
|     return new Promise((resolve, reject) => {
 @ ./js/index.js 6:0-30

ERROR in ./js/engine/version.jsx
Module parse failed: /home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-loader/index.js!/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/js/engine/version.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| export default "0.3.1";
 @ ./js/index.js 1:0-31

ERROR in ./js/engine/threads.jsx
Module parse failed: /home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-loader/index.js!/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/js/engine/threads.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import Database from "./database.jsx";
| import Helpers from "../libs/helpers.jsx";
| 
 @ ./js/index.js 8:0-31

ERROR in ./js/engine/z.jsx
Module parse failed: /home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-loader/index.js!/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/js/engine/z.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import ZeroFrame from "../libs/zero_frame.jsx";
| import Helpers from "../libs/helpers.jsx";
| 
 @ ./js/index.js 9:0-25

ERROR in ./js/engine/seen_count.jsx
Module parse failed: /home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/node_modules/babel-loader/index.js!/home/eric/Apps/ZeroNet-master/data/15k85k1Ex96Akt9UEinragwACRae9XS46q/js/engine/seen_count.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import Database from "./database.jsx";
| 
| class SeenCount {
 @ ./js/index.js 7:0-34

**Comment by sthetz** [comment]
It looks like you might not have installed required Webpack loaders. Are you sure you successfully ran command `npm install`? If so, please run command `npm list` in site's root and forward me its output.

**Comment by noflag** [comment]
Nullchan@0.1.0 /home/eric/Apps/nullchan
└── UNMET DEPENDENCY react-paginator@0.0.5 

npm ERR! missing: react-paginator@0.0.5, required by Nullchan@0.1.0 

On 2016-03-13 3:41 pm, Dmitriy Stetsenko wrote:

> It looks like you might not have installed required Webpack loaders. Are you sure you successfully ran command npm install? If so, please run command npm list in site's root and forward me its output. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/Nullchan/nullchan/issues/7#issuecomment-196073667

**Comment by sthetz** [comment]
Please run `npm install` in site's root once again and show me its output.

**Comment by noflag** [comment]
```
npm install
Nullchan@0.1.0 /home/eric/Apps/ZeroNet-master/data/1H7hUq6qsXRCRL2xaWUDuk4fwqd8PLGp7v
├─┬ babel-cli@6.6.5 
│ ├─┬ babel-core@6.7.2 
│ │ ├─┬ babel-code-frame@6.7.2 
│ │ │ ├── esutils@2.0.2 
│ │ │ ├── js-tokens@1.0.2 
│ │ │ ├─┬ line-numbers@0.2.0 
│ │ │ │ └── left-pad@0.0.3 
│ │ │ └─┬ repeating@1.1.3 
│ │ │   └─┬ is-finite@1.0.1 
│ │ │     └── number-is-nan@1.0.0 
│ │ ├─┬ babel-generator@6.7.2 
│ │ │ ├─┬ detect-indent@3.0.1 
│ │ │ │ └── get-stdin@4.0.1 
│ │ │ ├── is-integer@1.0.6 
│ │ │ └── trim-right@1.0.1 
│ │ ├── babel-helpers@6.6.0 
│ │ ├── babel-messages@6.7.2 
│ │ ├── babel-template@6.7.0 
│ │ ├─┬ babel-traverse@6.7.3 
│ │ │ ├── globals@8.18.0 
│ │ │ └── invariant@2.2.1 
│ │ ├─┬ babel-types@6.7.2 
│ │ │ └── to-fast-properties@1.0.1 
│ │ ├── babylon@6.7.0 
│ │ ├─┬ debug@2.2.0 
│ │ │ └── ms@0.7.1 
│ │ ├── json5@0.4.0 
│ │ ├─┬ minimatch@2.0.10 
│ │ │ └─┬ brace-expansion@1.1.3 
│ │ │   ├── balanced-match@0.3.0 
│ │ │   └── concat-map@0.0.1 
│ │ ├── private@0.1.6 
│ │ └── shebang-regex@1.0.0 
│ ├─┬ babel-polyfill@6.7.2 
│ │ ├── babel-regenerator-runtime@6.5.0 
│ │ └── core-js@2.1.5 
│ ├─┬ babel-register@6.7.2 
│ │ ├── core-js@2.1.5 
│ │ ├─┬ home-or-tmp@1.0.0 
│ │ │ └── os-tmpdir@1.0.1 
│ │ └─┬ source-map-support@0.2.10 
│ │   └── source-map@0.1.32 
│ ├─┬ babel-runtime@5.8.35 
│ │ └── core-js@1.2.6 
│ ├─┬ bin-version-check@2.1.0 
│ │ ├─┬ bin-version@1.0.4 
│ │ │ └─┬ find-versions@1.2.1 
│ │ │   ├── array-uniq@1.0.2 
│ │ │   ├─┬ meow@3.7.0 
│ │ │   │ ├─┬ camelcase-keys@2.0.0 
│ │ │   │ │ └── camelcase@2.1.1 
│ │ │   │ ├─┬ loud-rejection@1.3.0 
│ │ │   │ │ ├── array-find-index@1.0.1 
│ │ │   │ │ └── signal-exit@2.1.2 
│ │ │   │ ├── map-obj@1.0.1 
│ │ │   │ ├─┬ normalize-package-data@2.3.5 
│ │ │   │ │ ├── hosted-git-info@2.1.4 
│ │ │   │ │ ├─┬ is-builtin-module@1.0.0 
│ │ │   │ │ │ └── builtin-modules@1.1.1 
│ │ │   │ │ └─┬ validate-npm-package-license@3.0.1 
│ │ │   │ │   ├─┬ spdx-correct@1.0.2 
│ │ │   │ │   │ └── spdx-license-ids@1.2.0 
│ │ │   │ │   └─┬ spdx-expression-parse@1.0.2 
│ │ │   │ │     └── spdx-exceptions@1.0.4 
│ │ │   │ ├─┬ read-pkg-up@1.0.1 
│ │ │   │ │ ├─┬ find-up@1.1.2 
│ │ │   │ │ │ └── path-exists@2.1.0 
│ │ │   │ │ └─┬ read-pkg@1.1.0 
│ │ │   │ │   ├─┬ load-json-file@1.1.0 
│ │ │   │ │   │ ├─┬ parse-json@2.2.0 
│ │ │   │ │   │ │ └─┬ error-ex@1.3.0 
│ │ │   │ │   │ │   └── is-arrayish@0.2.1 
│ │ │   │ │   │ ├── pify@2.3.0 
│ │ │   │ │   │ └─┬ strip-bom@2.0.0 
│ │ │   │ │   │   └── is-utf8@0.2.1 
│ │ │   │ │   └── path-type@1.1.0 
│ │ │   │ ├─┬ redent@1.0.0 
│ │ │   │ │ ├─┬ indent-string@2.1.0 
│ │ │   │ │ │ └── repeating@2.0.0 
│ │ │   │ │ └── strip-indent@1.0.1 
│ │ │   │ └── trim-newlines@1.0.0 
│ │ │   └── semver-regex@1.0.0 
│ │ ├── minimist@1.2.0 
│ │ ├── semver@4.3.6 
│ │ └─┬ semver-truncate@1.1.0 
│ │   └── semver@5.1.0 
│ ├─┬ chalk@1.1.1 
│ │ ├─┬ ansi-styles@2.2.0 
│ │ │ └── color-convert@1.0.0 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ has-ansi@2.0.0 
│ │ │ └── ansi-regex@2.0.0 
│ │ ├── strip-ansi@3.0.1 
│ │ └── supports-color@2.0.0 
│ ├─┬ chokidar@1.4.3 
│ │ ├─┬ anymatch@1.3.0 
│ │ │ ├── arrify@1.0.1 
│ │ │ └─┬ micromatch@2.3.7 
│ │ │   ├─┬ arr-diff@2.0.0 
│ │ │   │ └── arr-flatten@1.0.1 
│ │ │   ├── array-unique@0.2.1 
│ │ │   ├─┬ braces@1.8.3 
│ │ │   │ ├─┬ expand-range@1.8.1 
│ │ │   │ │ └─┬ fill-range@2.2.3 
│ │ │   │ │   ├── is-number@2.1.0 
│ │ │   │ │   ├── isobject@2.0.0 
│ │ │   │ │   └── randomatic@1.1.5 
│ │ │   │ ├── preserve@0.2.0 
│ │ │   │ └── repeat-element@1.1.2 
│ │ │   ├── expand-brackets@0.1.4 
│ │ │   ├── extglob@0.3.2 
│ │ │   ├── filename-regex@2.0.0 
│ │ │   ├─┬ kind-of@3.0.2 
│ │ │   │ └── is-buffer@1.1.3 
│ │ │   ├── normalize-path@2.0.1 
│ │ │   ├─┬ object.omit@2.0.0 
│ │ │   │ ├─┬ for-own@0.1.3 
│ │ │   │ │ └── for-in@0.1.4 
│ │ │   │ └── is-extendable@0.1.1 
│ │ │   ├─┬ parse-glob@3.0.4 
│ │ │   │ ├── glob-base@0.3.0 
│ │ │   │ └── is-dotfile@1.0.2 
│ │ │   └─┬ regex-cache@0.4.2 
│ │ │     ├── is-equal-shallow@0.1.3 
│ │ │     └── is-primitive@2.0.0 
│ │ ├── async-each@1.0.0 
│ │ ├── glob-parent@2.0.0 
│ │ ├── inherits@2.0.1 
│ │ ├─┬ is-binary-path@1.0.1 
│ │ │ └── binary-extensions@1.4.0 
│ │ ├─┬ is-glob@2.0.1 
│ │ │ └── is-extglob@1.0.0 
│ │ └── readdirp@2.0.0 
│ ├─┬ commander@2.9.0 
│ │ └── graceful-readlink@1.0.1 
│ ├── convert-source-map@1.2.0 
│ ├── fs-readdir-recursive@0.1.2 
│ ├─┬ glob@5.0.15 
│ │ ├─┬ inflight@1.0.4 
│ │ │ └── wrappy@1.0.1 
│ │ └── once@1.3.3 
│ ├── lodash@3.10.1 
│ ├── log-symbols@1.0.2 
│ ├─┬ output-file-sync@1.1.1 
│ │ └── xtend@4.0.1 
│ ├── path-exists@1.0.0 
│ ├── path-is-absolute@1.0.0 
│ ├─┬ request@2.69.0 
│ │ ├── aws-sign2@0.6.0 
│ │ ├─┬ aws4@1.3.2 
│ │ │ └─┬ lru-cache@4.0.0 
│ │ │   ├── pseudomap@1.0.2 
│ │ │   └── yallist@2.0.0 
│ │ ├── bl@1.0.3 
│ │ ├── caseless@0.11.0 
│ │ ├─┬ combined-stream@1.0.5 
│ │ │ └── delayed-stream@1.0.0 
│ │ ├── extend@3.0.0 
│ │ ├── forever-agent@0.6.1 
│ │ ├── form-data@1.0.0-rc3 
│ │ ├─┬ har-validator@2.0.6 
│ │ │ ├─┬ is-my-json-valid@2.13.1 
│ │ │ │ ├── generate-function@2.0.0 
│ │ │ │ ├─┬ generate-object-property@1.2.0 
│ │ │ │ │ └── is-property@1.0.2 
│ │ │ │ └── jsonpointer@2.0.0 
│ │ │ └─┬ pinkie-promise@2.0.0 
│ │ │   └── pinkie@2.0.4 
│ │ ├─┬ hawk@3.1.3 
│ │ │ ├── boom@2.10.1 
│ │ │ ├── cryptiles@2.0.5 
│ │ │ ├── hoek@2.16.3 
│ │ │ └── sntp@1.0.9 
│ │ ├─┬ http-signature@1.1.1 
│ │ │ ├── assert-plus@0.2.0 
│ │ │ ├─┬ jsprim@1.2.2 
│ │ │ │ ├── extsprintf@1.0.2 
│ │ │ │ ├── json-schema@0.2.2 
│ │ │ │ └── verror@1.3.6 
│ │ │ └─┬ sshpk@1.7.4 
│ │ │   ├── asn1@0.2.3 
│ │ │   ├─┬ dashdash@1.13.0 
│ │ │   │ └── assert-plus@1.0.0 
│ │ │   ├── ecc-jsbn@0.1.1 
│ │ │   ├── jodid25519@1.0.2 
│ │ │   ├── jsbn@0.1.0 
│ │ │   └── tweetnacl@0.14.1 
│ │ ├── is-typedarray@1.0.0 
│ │ ├── isstream@0.1.2 
│ │ ├── json-stringify-safe@5.0.1 
│ │ ├─┬ mime-types@2.1.10 
│ │ │ └── mime-db@1.22.0 
│ │ ├── node-uuid@1.4.7 
│ │ ├── oauth-sign@0.8.1 
│ │ ├── qs@6.0.2 
│ │ ├── stringstream@0.0.5 
│ │ ├── tough-cookie@2.2.2 
│ │ └── tunnel-agent@0.4.2 
│ ├── slash@1.0.0 
│ ├── source-map@0.5.3 
│ └─┬ v8flags@2.0.11 
│   └── user-home@1.1.1 
├─┬ babel-loader@6.2.4 
│ ├─┬ loader-utils@0.2.12 
│ │ └── big.js@3.1.3 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ └── object-assign@4.0.1 
├─┬ babel-preset-es2015@6.6.0 
│ ├── babel-plugin-check-es2015-constants@6.7.2 
│ ├── babel-plugin-transform-es2015-arrow-functions@6.5.2 
│ ├── babel-plugin-transform-es2015-block-scoped-functions@6.6.5 
│ ├── babel-plugin-transform-es2015-block-scoping@6.7.1 
│ ├─┬ babel-plugin-transform-es2015-classes@6.6.5 
│ │ ├── babel-helper-define-map@6.6.5 
│ │ ├── babel-helper-function-name@6.6.0 
│ │ ├── babel-helper-optimise-call-expression@6.6.0 
│ │ └── babel-helper-replace-supers@6.7.0 
│ ├── babel-plugin-transform-es2015-computed-properties@6.6.5 
│ ├── babel-plugin-transform-es2015-destructuring@6.6.5 
│ ├── babel-plugin-transform-es2015-duplicate-keys@6.6.4 
│ ├── babel-plugin-transform-es2015-for-of@6.6.0 
│ ├── babel-plugin-transform-es2015-function-name@6.5.0 
│ ├── babel-plugin-transform-es2015-literals@6.5.0 
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.7.0 
│ │ └── babel-plugin-transform-strict-mode@6.6.5 
│ ├── babel-plugin-transform-es2015-object-super@6.6.5 
│ ├─┬ babel-plugin-transform-es2015-parameters@6.7.0 
│ │ ├─┬ babel-helper-call-delegate@6.6.5 
│ │ │ └── babel-helper-hoist-variables@6.6.5 
│ │ └── babel-helper-get-function-arity@6.6.5 
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.5.0 
│ ├── babel-plugin-transform-es2015-spread@6.6.5 
│ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.5.0 
│ │ └── babel-helper-regex@6.6.5 
│ ├── babel-plugin-transform-es2015-template-literals@6.6.5 
│ ├── babel-plugin-transform-es2015-typeof-symbol@6.6.0 
│ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.5.0 
│ │ └─┬ regexpu-core@1.0.0 
│ │   ├── regenerate@1.2.1 
│ │   ├── regjsgen@0.2.0 
│ │   └─┬ regjsparser@0.1.5 
│ │     └── jsesc@0.5.0 
│ └─┬ babel-plugin-transform-regenerator@6.6.5 
│   └── babel-plugin-syntax-async-functions@6.5.0 
├─┬ babel-preset-react@6.5.0 
│ ├── babel-plugin-syntax-flow@6.5.0 
│ ├── babel-plugin-syntax-jsx@6.5.0 
│ ├── babel-plugin-transform-flow-strip-types@6.7.0 
│ ├── babel-plugin-transform-react-display-name@6.5.0 
│ ├─┬ babel-plugin-transform-react-jsx@6.6.5 
│ │ └── babel-helper-builder-react-jsx@6.6.5 
│ └── babel-plugin-transform-react-jsx-source@6.5.0 
├── UNMET PEER DEPENDENCY lodash@>= 4.3.0 < 5.0.0
├─┬ react@0.14.7 
│ ├─┬ envify@3.4.0 
│ │ ├─┬ jstransform@10.1.0 
│ │ │ ├── base62@0.1.1 
│ │ │ ├── esprima-fb@13001.1001.0-dev-harmony-fb 
│ │ │ └── source-map@0.1.31 
│ │ └── through@2.3.8 
│ └─┬ fbjs@0.6.1 
│   ├── loose-envify@1.1.0 
│   ├─┬ promise@7.1.1 
│   │ └── asap@2.0.3 
│   ├── ua-parser-js@0.7.10 
│   └── whatwg-fetch@0.9.0 
├── react-dom@0.14.7 
├── react-pagify@2.0.1 
├── react-paginator@0.0.5 
├── segmentize@0.4.1 
├─┬ uglify-loader@1.3.0 
│ └─┬ uglify-js@2.6.2 
│   ├── async@0.2.10 
│   └─┬ yargs@3.10.0 
│     ├── camelcase@1.2.1 
│     ├─┬ cliui@2.1.0 
│     │ ├─┬ center-align@0.1.3 
│     │ │ ├─┬ align-text@0.1.4 
│     │ │ │ ├── longest@1.0.1 
│     │ │ │ └── repeat-string@1.5.4 
│     │ │ └── lazy-cache@1.0.3 
│     │ └── right-align@0.1.3 
│     ├── decamelize@1.2.0 
│     └── window-size@0.1.0 
├─┬ uglifyjs@2.4.10 
│ ├── async@0.2.10 
│ ├─┬ source-map@0.1.34 
│ │ └── amdefine@1.0.0 
│ ├── uglify-to-browserify@1.0.2 
│ └── yargs@1.3.3 
└─┬ webpack@1.12.14 
  ├── async@1.5.2 
  ├── clone@1.0.2 
  ├─┬ enhanced-resolve@0.9.1 
  │ ├── graceful-fs@4.1.3 
  │ └── memory-fs@0.2.0 
  ├── esprima@2.7.2 
  ├── interpret@0.6.6 
  ├─┬ memory-fs@0.3.0 
  │ ├─┬ errno@0.1.4 
  │ │ └── prr@0.0.0 
  │ └─┬ readable-stream@2.0.6 
  │   ├── core-util-is@1.0.2 
  │   ├── isarray@1.0.0 
  │   ├── process-nextick-args@1.0.6 
  │   └── util-deprecate@1.0.2 
  ├─┬ node-libs-browser@0.5.3 
  │ ├── assert@1.3.0 
  │ ├─┬ browserify-zlib@0.1.4 
  │ │ └── pako@0.2.8 
  │ ├─┬ buffer@3.6.0 
  │ │ ├── base64-js@0.0.8 
  │ │ ├── ieee754@1.1.6 
  │ │ └── isarray@1.0.0 
  │ ├─┬ console-browserify@1.1.0 
  │ │ └── date-now@0.1.4 
  │ ├── constants-browserify@0.0.1 
  │ ├─┬ crypto-browserify@3.2.8 
  │ │ ├── pbkdf2-compat@2.0.1 
  │ │ ├── ripemd160@0.2.0 
  │ │ └── sha.js@2.2.6 
  │ ├── domain-browser@1.1.7 
  │ ├── events@1.1.0 
  │ ├─┬ http-browserify@1.7.0 
  │ │ └── Base64@0.2.1 
  │ ├── https-browserify@0.0.0 
  │ ├── os-browserify@0.1.2 
  │ ├── path-browserify@0.0.0 
  │ ├── process@0.11.2 
  │ ├── punycode@1.4.0 
  │ ├── querystring-es3@0.2.1 
  │ ├─┬ readable-stream@1.1.13 
  │ │ └── isarray@0.0.1 
  │ ├─┬ stream-browserify@1.0.0 
  │ │ └── readable-stream@1.1.13 
  │ ├── string_decoder@0.10.31 
  │ ├── timers-browserify@1.4.2 
  │ ├── tty-browserify@0.0.0 
  │ ├─┬ url@0.10.3 
  │ │ ├── punycode@1.3.2 
  │ │ └── querystring@0.2.0 
  │ ├── util@0.10.3 
  │ └─┬ vm-browserify@0.0.4 
  │   └── indexof@0.0.1 
  ├─┬ optimist@0.6.1 
  │ ├── minimist@0.0.10 
  │ └── wordwrap@0.0.2 
  ├─┬ supports-color@3.1.2 
  │ └── has-flag@1.0.0 
  ├── tapable@0.1.10 
  ├─┬ uglify-js@2.6.2 
  │ └── async@0.2.10 
  ├─┬ watchpack@0.2.9 
  │ └── async@0.9.2 
  └─┬ webpack-core@0.6.8 
    ├── source-list-map@0.1.5 
    └── source-map@0.4.4 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN react-pagify@2.0.1 requires a peer of lodash@>= 4.3.0 < 5.0.0 but none was installed.
npm WARN Nullchan@0.1.0 No repository field.
npm WARN Nullchan@0.1.0 No license field.
```

**Comment by sthetz** [comment]
As far as I can say it looks like one of dependencies can work on OSX only (I'm new with Node so I might be mistaken). 

Please tell me which Linux distro do you use so I will test test this on virtual machine.

**Comment by noflag** [comment]
Linux Mint 17.3 Rosa 64bit

**Comment by Omega9** [comment]
Same issue.
Mint 17.3 x64 too.

**Comment by clownfeces** [comment]
Here's a tutorial on how to clone nullchan: 
http://127.0.0.1:43110/zupport.bit/?/zupport/thread/60c4680da68c0c271b2ba411e3c83b71
